version: 2
orbs:
  commands:
    configure-aws:
      - aws-cli/configure:
          aws-access-key-id: $OPS_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $OPS_AWS_SECRET_ACCESS_KEY
          aws-region: us-east-1
          profile-name: datacamp-test
jobs:
  build:
    docker:
      - image: regviz/node-xcb
    working_directory: ~/repo
      - checkout
    # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: npm test
      - run: npm run reg-suit